services:
  - type: web
    name: fb-multi-poster-auth
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_AUTH_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
